### ISSUE TITLE
No way to adjust for locale de-CH

### ISSUE THREAD

**Issue by jassonmc** [ONLYOFFICE/snap-desktopeditors#109] opened 2024-02-14 09:41 UTC
Hello there

I am Swiss and am only able to choose "German" as Language, but no way to adjust for Swiss German.
That way the new.docx that's used to create new documents is from here:

/snap/onlyoffice-desktopeditors/current/opt/onlyoffice/desktopeditors/converter/empty/de-DE

With that, spell checking used is German and not Swiss German, which is quite different.

Is it possible to come up with German (Switzerland) as a Language and have the templates in there use German Switzerland for spell checker?
The new template folder would then probably be:
/snap/onlyoffice-desktopeditors/current/opt/onlyoffice/desktopeditors/converter/empty/de-CH

In the meantime, is there a workaround for Swiss German spell checking as a default on creating new documents?

Thanks for any hint

EDIT:
In extension to the limitations of the snap format, is there a generic way to point to a certain folder for the templates of new files?
If there would be a way to override the default path
/snap/onlyoffice-desktopeditors/current/opt/onlyoffice/desktopeditors/converter/empty/...

That would make so many things a ton easier, especially for business environments, where corporate templates are a must.

**Comment by matveevms** [comment] 2024-02-15 13:14
Hello. This is a known enhancement request ticket 61460. Our developers are already thinking about this improvement.
Unfortunately, there is currently no workaround for being able to set a different default spellcheck language.
Thank you for your request.

**Comment by Rita-Bubnova** [comment] 2024-02-15 13:16
Duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/1223.

**Closed by Rita-Bubnova** 2024-02-15 13:16 UTC

**Comment by jassonmc** [comment] 2024-02-19 20:49
Good to hear, that this issue is on your radar.
May I make a super simple suggestion?

Why not define a fixed path for custom templates?
The path should NOT be inside a user profile, but rather only possible to be set by an administrator, maybe /etc/onlyoffice-desktopeditors/customtemplates/new.docx

If that would exist, do not use the locale specific templates, but the custom ones.

That would not only help solve the problem with missing locales, but also allow for an easy way to provide custom new.docx, for what ever reason, mainly for CI/CD reasons.
